<section class="add-user">
    <div class="wrapper box">
        <h2>Új admin felhasználó felvétele</h2>
        <div class="form-outer">
            <div class="form-head">
                <h3>Felhasználó adatok megadása</h3>
            </div>
            <div class="clearfix"></div>
            <form id="edit-f" action="/admin/addAdmin" method="post">
                <input type="hidden" name="sent" value="1">
                <div class="form-group">
                    <div class="text">
                        <span>Név:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="name" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>E-mail cím:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="email" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>Jelszó:</span>
                    </div>
                    <div class="form-field input">
                        <input type="password" name="password" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>Jelszó mégegyszer:</span>
                    </div>
                    <div class="form-field input">
                        <input type="password" name="password2" required>
                    </div>
                </div>
                <div class="form-field">
                    <button type="submit" class="submit upper">Regisztrálás</button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</section>