<section class="add-user">
    <div class="wrapper box">
        <h2>Új alapadat felvétele</h2>
        <div class="form-outer">
            <div class="form-head">
                <h3>Adatok megadása</h3>
            </div>
            <div class="clearfix"></div>
            <form id="edit-f" action="<?php echo $_SERVER["REQUEST_URI"]?>" method="post">
                <input type="hidden" name="sent" value="1">
                <div class="form-group">
                    <div class="text">
                        <span>Név:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="name" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>Érték:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="value" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-field r-selection">
                        <span>Szükséges:</span>
                        <input type="radio" name="required" value="1" id="req">
                        <label for="req">igen</label>
                        <input type="radio" name="required" value="0" id="noreq" checked>
                        <label for="noreq">Nem</label>
                    </div>
                </div>
                <div class="form-field">
                    <button type="submit" class="submit upper">Felvétel</button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</section>