<section class="add-gallery">
    <div class="wrapper box">
        <h2>Új Galéria felvétele</h2>
        <div class="form-outer">
            <div class="form-head">
                <h3>Adatok megadása</h3>
            </div>
            <div class="clearfix"></div>
            <form id="edit-f" action="<?php echo $_SERVER["REQUEST_URI"]?>" method="post">
                <input type="hidden" name="sent" value="1">
                <div class="form-group">
                    <div class="text">
                        <span>Név:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="name" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>Uri:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="uri" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>Borítókép:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="cover" required>
                    </div>
                </div>
                <div class="form-field">
                    <button type="submit" class="submit upper">Felvétel</button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</section>