<section class="add-user">
    <div class="wrapper box">
        <h2>Új menü hozzáadása</h2>
        <div class="form-outer">
            <div class="form-head">
                <h3>Adatok megadása</h3>
            </div>
            <div class="clearfix"></div>
            <form id="edit-f" action="<?php echo $_SERVER["REQUEST_URI"]?>" method="post">
                <input type="hidden" name="sent" value="1">
                <div class="form-group">
                    <div class="text">
                        <span>Név:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="name" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>Url:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="src" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-field r-selection">
                        <span>Pozició:</span>
                        <input type="radio" name="position" value="header" id="header" checked>
                        <label for="header">Fejléc</label>
                        <input type="radio" name="position" value="footer" id="footer">
                        <label for="footer">Lábléc</label>
                        <div class="form-group level animate">
                            <div class="form-field r-selection">
                                <span>Szint:</span>
                                <input type="radio" name="level" value="0" id="first" checked>
                                <label for="first">Első</label>
                                <input type="radio" name="level" value="1" id="sec">
                                <label for="sec">Második</label>
                                <div class="form-group parent animate">
                                    <div class="form-field r-selection r-select">
                                        <span>Szülő:</span>
                                        <select name="parent">
                                            <optgroup label="Header">
                                                <option value="">--Válasszon szülőt--</option>
<?php foreach ($datas as $parent):
        if (!$parent->level): ?>
                                                <option value="<?php echo $parent->id?>"><?php echo $parent->name?></option>
<?php   endif;
      endforeach; ?>
                                            </optgroup>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="form-field r-selection">
                        <span>Munkamenet:</span>
                        <input type="radio" name="need_session" value="1" id="session" checked>
                        <label for="session">Igen</label>
                        <input type="radio" name="need_session" value="0" id="nosession">
                        <label for="nosession">Nem</label>
                    </div>
                </div>
                <div class="form-field">
                    <button type="submit" class="submit upper">Felvétel</button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</section>