<section class="edit-admin">
    <div class="wrapper box">
        <h2>Admin adatok módosítása</h2>
        <div class="form-outer">
            <div class="form-head">
                <h3><?php echo $user->name?> - Adatok szerkesztése</h3>
            </div>
            <div class="clearfix"></div>
            <form id="edit-f" action="<?php echo $_SERVER["REQUEST_URI"] ?>" method="post">
                <input type="hidden" name="sent" value="1">
                <div class="form-group">
                    <div class="text">
                        <span>Név:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="name" value="<?php echo $user->name?>">
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>E-mail cím:</span>
                    </div>
                    <div class="form-field input">
                        <input type="text" name="email" value="<?php echo $user->email?>">
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>Jelszó:</span>
                    </div>
                    <div class="form-field input">
                        <input type="password" name="password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="text">
                        <span>Jelszó mégegyszer:</span>
                    </div>
                    <div class="form-field input">
                        <input type="password" name="password2">
                    </div>
                </div>
<?php if (!$user->sys_admin || $user->id != $admin->id) :?>
                <div class="form-group outer remove">
                    <div class="text">
                        <span>Törlés:</span>
                    </div>
                    <div class="form-field text">
                        <a href="/admin/deleteAdmin/<?php echo $user->id?>" class="submit">Törlés</a>
                    </div>
                </div>
<?php endif;?>
                <div class="form-field">
                    <button type="submit" class="submit upper">Módosít</button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</section>