<section class="admin-login">
    <div class="wrapper box">
        <div class="form-outer">
            <div class="form-head">
                <h2>Bejelentkezés - Admin</h2>
            </div>
            <form id="a-login" action="/admin" method="post">
                <input type="hidden" name="sent" value="1">
                <div class="form-field input">
                    <input type="text" placeholder="E-mail" name="email">
                </div>
                <div class="form-field input">
                    <input type="password" placeholder="Jelszó" name="password">
                </div>
                <div class="form-field">
                    <button class="submit" type="submit" >Bejelentkezés</button>
                </div>
            </form>
        </div>
        <?php if (isset($error)) {
            echo $error;
        }?>


    </div>
</section>