<section class="re-activate wrapper box">
    <div class="form-outer">
        <div class="form-head">
            <h2>Fiók beaktiválása</h2>
        </div>
        <form action="/repassword/activate" method="post">
            <div class="form-group">
                <input type="hidden" name="sent" value="1">
                <div class="text">
                    <span>E-mail cím:</span>
                </div>
                <div class="form-field input">
                    <input type="text" name="email" placeholder="E-mail cím" required>
                </div>
            </div>
            <div class="form-group">
                <div class="text">
                    <span>Aktivációs kód:</span>
                </div>
                <div class="form-field input">
                    <input type="text" name="code" placeholder="Aktivációs kód" required>
                </div>
            </div>
            <div class="form-field">
                <button class="submit upper" type="submit">Elküldés</button>
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
    <div class="desc">
        <div class="desc-head">
            <b>Új jelszó igénylése</b>
        </div>
        <div class="desc-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
             Etiam non blandit massa, mattis tempus nulla. Sed in nunc ante.
              Sed faucibus mattis vehicula. Quisque varius enim non nibh fringilla,
               ut pulvinar nisl fermentum. Pellentesque sit amet sapien lobortis dolor faucibus
                tincidunt sit amet ut erat. Nam porttitor elementum mauris sed pretium.
                 Mauris mattis tellus at egestas cursus. Proin congue lacinia viverra.
                  Quisque sagittis sollicitudin tempor. Duis convallis lacinia venenatis.
                   Morbi a sapien volutpat, cursus arcu vel, aliquet risus. Vestibulum facilisis
                    iaculis tortor, vel ullamcorper sem consectetur at. Pellentesque sed
                     lacinia felis. Vestibulum neque quam, sollicitudin at tempor eget,
                      tincidunt ac magna. Pellentesque habitant morbi tristique senectus
                       et netus et malesuada fames ac turpis egestas. Pellentesque finibus
                        diam non finibus ullamcorper.
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
             Etiam non blandit massa, mattis tempus nulla. Pellentesque sed
             lacinia felis. Vestibulum neque quam, sollicitudin at tempor eget,
              tincidunt ac magna. Pellentesque habitant morbi tristique senectus
               et netus et malesuada fames ac turpis egestas. Pellentesque finibus
                diam non finibus ullamcorper.
            </p>
        </div>
    </div>
    <div class="clearfix"></div>
</section>