<?php
use core\classes\session;
?>
    </main>
    <div class="clearfix"></div>
    <div id="button">
        <input type="checkbox" id="toggler">
        <label for="toggler">#CLICK ME#</label>
    </div>
    <footer>
        <div class="wrapper box">
            <div class="footer-menu in-b">
                <nav>
                    <ul>
<?php if (!session::check("user")) {?>
<?php foreach ($menus as $item):?>
<?php if ($item->position == 'footer' && !$item->need_session):?>
                            <li class="in-b"><a href="<?php echo $item->src; ?>"><?php echo $item->name; ?></a>
<?php endif; ?>
<?php endforeach; ?>
<?php } else {?>
<?php foreach ($menus as $item):?>
<?php if ($item->position == 'footer' && $item->need_session): ?>
                            <li class="in-b"><a href="<?php echo $item->src; ?>"><?php echo $item->name; ?></a>
<?php endif; ?>
<?php endforeach;?>
<?php }?>
                    </ul>
                </nav>
            </div>
            <div class="footer-logo right">
                <a href="/">
                    <?php echo file_get_contents("assets/img/logo-b-full-leaf.svg")?>
                </a>
            </div>
            <div class="footer-brands in-b">
                <div class="footer-copy">
                    <span class="company">&copy; <?php echo $GLOBALS["config"]["companyName"]?></span>
                    <span class="time"><?php echo $GLOBALS["config"]["dateTime"]?> - <?php echo date("Y")?></span>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </footer>
    <div class="clearfix"></div>
    <?php $self->outputJs(); ?>
</body>
</html>