<?php
use core\classes\session;
?>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="apple-touch-icon" sizes="57x57" href="/assets/img/favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/assets/img/favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/assets/img/favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/assets/img/favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/assets/img/favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/assets/img/favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/assets/img/favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/assets/img/favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/assets/img/favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/assets/img/favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicon/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
<title><?php echo $GLOBALS["config"]["companyName"] . " - Admin" ?></title>
    <?php $self->outputCss(); ?>
</head>
<body>
<?php if ($_SERVER["REQUEST_URI"] != "/admin"  && session::check("admin")){?>
    <div id="header-ph"></div>
    <div id="logo">
        <a href="/admin/dashboard">
            <?php echo file_get_contents("assets/img/logo-b-full-leaf.svg")?>
        </a>
    </div>
    <header>
        <div class="wrapper box">
            <div class="a-menu desktop">
                <nav>
                    <ul>
                        <li class="in-b"><a href="/" title="Honlap"><?php echo $GLOBALS["config"]["domain"]?></a></li>
                        <li class="in-b"><a href="/admin/messages" title="Képek">Üzenetek</a></li>
                        <li class="in-b"><a href="/admin/notes" title="Képek">Értesítések</a></li>
                    </ul>
                </nav>
            </div>
<?php if ($_SERVER["REQUEST_URI"] != "/admin" && session::check("admin")) {?>
                <div class="a-controls">
                    <div class="menu-open white in-b mobile">
                        <label for="toggle-sb">
                            <i class="fas fa-bars"></i>
                        </label>
                    </div>
                    <div class="logout">
                        <li>
                            <a href="/admin/logout">
                                <span class="desktop" alt="Kijelentkezés">Kijelentkezés</span>
                            </a>
                        </li>
                    </div>
                </div>
<?php }?>
        </div>
    </header>
<?php }?>
    <div class="clearfix"></div>
    <main>